nginx:
  build: ./nginx
  links:
    - web:web
  ports:
    - 80:80

web:
  build: ./ruby
  working_dir: /app
  command: rackup -o 0.0.0.0 -p 9292
  ports:
    - 127.0.0.1:9292:9292
  links:
    - memcached:memcached

memcached:
  build: ./memcached
  ports:
    - 127.0.0.1:11211:11211
